name: Testing SAST Gate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tfsec_scan:
    name: tfsec SAST Scanner
    # Spins temp linux virtual runner in GitHub's cloud to run checks
    runs-on: ubuntu-latest

    steps:
      # Pulls copy of repo into virtual runner so tools can see code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Runs the tfsec scanner across terraform files
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false
          # CRITICAL - instructs the pipeline to return a non-zero exit code and block deployment
