name: Security Quality Gate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    name: tfsec SAST Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false
