name: Security Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    name: tfsec SAST Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec Scan
        run: |
          tfsec . --soft-fail=false
